version: "3"

services:
  web:
    container_name: mon-ip
    image: mon-ip_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_NGINX_IMAGE: ${DOCKER_PHP_NGINX_IMAGE:-webdevops/php-nginx:8.3}
    ports:
      - ${DOCKER_WEB_PORT:-82}:80
    volumes:
      - .:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  database:
    container_name: mon-ip_mysql
    image: mysql:8.0.40
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD:-root}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE:-mon-ip}
      - MYSQL_USER=${DOCKER_MYSQL_USER:-mon-ip}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD:-ChangeMe}
    ports:
      - ${DOCKER_MYSQL_PORT:-3302}:3306